allow for shared or global model extension when rendering all ingredi…
RetailMeNotSandbox/roux-server pull request #15
Opened 2016-12-16 20:00 UTC by lzilioli

There may be cases where you want to specify global model properties that are always included when rendering a preview, regardless of ingredient.

This change makes that possible.

2017-01-09 18:59 UTC, lawnsea commented
Can you explain the motivation for this a bit more, please? I would expect this to be done via `model.js` in the ingredient.

2017-01-09 19:04 UTC, lzilioli commented
@lawnsea the motivation is that certain things (icons.svg) remain as something all ingredients expect to have available to their model. It would be redundant/unnecessary to expose the icons by hand in every ingredient.

The stash PR associated with bechamel illustrates how this change is used.

2017-02-16 17:31 UTC, lzilioli commented
@lawnsea I still think we need to land this or something like it. The module allows you to override the `defaultPreviewTemplatePath` with a template owned by the consuming module, but roux-server provides no way to modify the model that is used to render the templates.

It is not very useful to let me override the default-preview unless I also have some level of control over the model that is thrown at that preview template.

2017-02-17 23:22 UTC, lawnsea commented on lib/middleware/preview.js
> + *   your ingredients assume will be in their model at all times.
Ok, so what you're proposing is the ability to specify a base for the preview model as well as a base for the ingredient model. If we land this, let's call these properties `basePreviewModel` and `baseModel` or smth like that.

2017-02-17 23:34 UTC, lawnsea commented
> certain things (icons.svg) remain as something all ingredients expect to have available to their model

Just so I'm clear, you mean that they expect them to appear at a particular absolute path in the model, right? Specifically, the templates reference `@root.page.svgImagePath`.

> It is not very useful to let me override the default-preview unless I also have some level of control over the model that is thrown at that preview template.

This is a compelling argument. I'm in favor of landing this if you remove the unnecessary `commonModel` config and rename `globalModel` to `basePreviewModel`.

2017-02-17 23:36 UTC, lawnsea requested changes
This looks ok, but I'd like to remove the `commonModel` code and rename `globalModel` to `basePreviewModel`.

2017-02-17 23:36 UTC, lawnsea commented on lib/middleware/preview.js
> + * @param {Object} [config.commonModel] - optional model that will be extended
I don't think we need this. The ingredients should instead require a common base model in their `model.js` entrypoint.

2017-02-17 23:36 UTC, lawnsea commented on lib/middleware/preview.js
> + * @param {Object} [config.globalModel] - optional model that will be extended
This is really a base preview model. Let's call it `basePreviewModel`.

2017-02-20 16:59 UTC, merged

2017-02-20 17:01 UTC, lzilioli commented
Published in v1.0.2